# Generated by Django 4.1 on 2022-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prtofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skintype', models.CharField(choices=[('D', 'Dry'), ('C', 'Combination'), ('O', 'Oily')], default='D', max_length=1)),
            ],
        ),
    ]
