# Generated by Django 4.1 on 2022-08-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prtofile',
            new_name='Profile',
        ),
    ]
