# Generated by Django 4.1 on 2022-08-12 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='howto',
            field=models.CharField(choices=[('A', 'AM'), ('B', 'AM & PM'), ('P', 'PM')], default='A', max_length=1),
        ),
    ]
