# Generated by Django 4.1 on 2022-08-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_profile_com'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='com',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skintype',
            new_name='skin_type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='howto',
            new_name='time',
        ),
    ]
